version: '2'
services:

  node:
    build: .
    image: "${TODO_IMAGE}"
    links:
      - mongo
    ports:
      - "80:8080"
    environment:
      MONGODB_URI: "mongodb://mongo:27017/todo"

  mongo:
    image: mongo:2.6.11
    command: mongod --smallfiles
